/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws IOException {
        File location = new File("src/main/resources/gates.js");
        fileScanner(location);

    }

    public static String fileScanner(File location) {
        int counter = 1;
        String result = "";
        try {
            Scanner readThru = new Scanner(location);
            String nextLine;

            while (readThru.hasNext()) {
                nextLine = readThru.nextLine();
                boolean conditionA = nextLine.endsWith(";");
                boolean conditionB = nextLine.endsWith("{");
                boolean conditionC = nextLine.endsWith("}");
                boolean conditionD = nextLine.endsWith("if");
                boolean conditionE = nextLine.endsWith("else");
                boolean conditionF = nextLine.isBlank();

                if ((!conditionA) && !conditionB && !conditionC && !conditionD && !conditionE && !conditionF) {
                    result += "Line " + counter + " Missing semicolon\n";
                }
                counter++;
            }


            } catch(FileNotFoundException e){
                System.out.println("File is not available");
            }
        return result;

        }
    }