/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

//test feature1
public class LibraryTest {
    @Test public void testRollMethod(){
        int number=4;
        int[]result = Library.roll(number);
        assertEquals(number,result.length);
    }

    @Test public void  testRollBetweenOneAndSix(){
        int[] result = Library.roll(3);
        for (int number:result){
            boolean actual =number>0 &&number<4;
            System.out.println("actual = "+actual);
            assertTrue(actual);

        }

        }
     @Test public void testContainsDuplicates(){
         int[] findDuplicates = new int[]{18,20,21,22,23,25,25,32};
         assertTrue("This will check for duplicate values", Library.containsDuplicates(findDuplicates));
     }

    @Test public void testCalculateAverage(){
        int[] findAverage = new int[]{2,5,8,10};
        double theAverage = Library.calculateAverage(findAverage);
        assertTrue("The average value for this array is", theAverage == 6.25);
    }



     @Test public void testMulArraysMethod() {
         int[][] weeklyMonthTemperatures = {
                 {66, 64, 58, 65, 71, 57, 60},
                 {57, 65, 65, 70, 72, 65, 51},
                 {55, 54, 60, 53, 59, 57, 61},
                 {65, 56, 55, 52, 55, 62, 57}
         };
         int actual = Library.mulArrays(weeklyMonthTemperatures);
         int expected = 57;
         assertEquals(expected, actual);
     }
    }

