/*
 * This Java source file was generated by the Gradle 'init' task.
 */

 package basiclibrary;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Random;

public class Library {

    // Rolling Dice

    public static void main(String[] args) {

        System.out.println(Arrays.toString(roll(5)));
    }

    public static int[] roll(int num) {

        int[] numberShowsInArray = new int[num];

        Random rand = new Random();
        for (int i = 0; i < num; i++) {
            rand.nextInt(6);
            numberShowsInArray[i] = (rand.nextInt(6) + 1);
        }
        return numberShowsInArray;


    }


// containsDuplicates

    public static boolean containsDuplicates(int[] arr) {
        for (int i = 0; i < arr.length; i++) {
            for (int j = 1; j < arr.length; j++) {
                if (arr[i] == arr[j] && i != j)
                    return true;
            }
        }
        return false;
    }


//Calculating Averages

    public static double calculateAverage(int[] array){

        double sum = 0;
        for(int i = 0; i < array.length; i++){
            sum = sum + array[i];
        }
        double result = sum / array.length;
        return result;
    }


//Arrays of Arrays
public static int mulArrays(int[][] arr) {
    int lowestAvg = 100;
    for (int i = 0; i < arr.length; i++) {
        int total = 0;
        int avg;
        for (int k = 0; k <arr[i].length; k++) {
            total = total + arr[i][k];
        }
        avg = total/(arr[i].length);
        if (avg < lowestAvg) {
            lowestAvg = avg;
        }
    }
    return lowestAvg;
}

//Analyzing Weather Data
HashMap<String,Integer> weatherData = new HashMap<>();





}





