/*
 * This Java source file was generated by the Gradle 'init' task.
 */

// package basiclibrary;

import java.util.Arrays;
import java.util.Random;

public class Library {

    // Rolling Dice

    public static void main(String[] args) {
       
        System.out.println(Arrays.toString(roll(5)));
    }

    public static int[] roll(int num) {

        int[] numberShowsInArray = new int[num];

        Random rand = new Random();
        for (int i = 0; i < num; i++) {
            rand.nextInt(6);
            numberShowsInArray[i] = (rand.nextInt(6) + 1);
        }
        return numberShowsInArray;
        //Contains Duplicates
        public static boolean containsDuplicates(int num) {
            while(int j=0;j<num;j++){
               
            
    }











}